# External plugins
# See http://ixti.net/software/2013/01/28/using-jekyll-plugins-on-github-pages.html for making `jekyll archives` work.
gems:
- jekyll-archives
- jekyll-sitemap
- jekyll-paginate

exclude:
  - "/vendor/"

title: bbarkji's tech diary
subtitle: "study and write"
email: barkji0@naver.com
name: Jiyeong Park
description: 
baseurl: ""
url: https://brightjy.github.io
plugins_dir: 
- jekyll-sitemap
cover: "/assets/header_image.jpg"
logo: "/assets/logo.jpg"
markdown: kramdown
hightlighter: rouge
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: true
highlightjs_theme: monokai-sublime

#pagination:
  #enabled: true
  #per_page: 5
  #permalink: "/page/:num/"
  #sort_reverse: true

jekyll-archives:
  enabled:
    - categories
    - tags
  layout: archive
  comment: true
  permalinks:
    category: "/category/:name/"
    tag: "/tag/:name/"

descriptions:
  - cat: jekyll
    desc: Posts describing Jekyll setup techniques.

  - cat: dummy
    desc: Just some placeholder posts, lorem ipsum and the rest.

  - cat: java

social:
  - name: GitHub
    icon: github
    username: brightjy
    url: https://github.com/brightjy
    desc: Fork me on GitHub
    share: false

  - name: Instagram
    icon: instagram
    username: bbarkji
    url: https://www.instagram.com/bbarkji/
    desc: Follow me on Instagram
    share: false

protocols:
    fb_image: "/assets/logo.jpg"
    fb_image_width: 612
    fb_image_height: 605
    fb_image_type: "image/jpg"

    twitter_image: "/assets/logo.jpg"

    os_repo: https://github.com/brightjy/brightjy.github.io
    os_rcs_type: git
    os_src: git@github.com:bencentra/centrarium.com.git
